Allow tagged literals, remove withStyles naming
tizmagik/react-csjs pull request #9
Opened 2016-10-10 08:12 UTC by drcmda

This allows react-csjs to be used as a decorator and literal tag at the same time. Since "withStyles" is the default export, the name is arbitrary. It can be exported as csjs, thereby removing the need for the additional "csjs" import, also postCSS transforms will work.

´´´ js
import csjs from 'react-csjs';

@csjs`
.figure {
    margin: 0;
    width: 100%;
    position: relative;
    min-height: 100vh;
    padding: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    & > span {
        padding: 0 30%;
        font-size: 1.5em;
    }
}`
export default class Figure extends React.Component {
    render() {
´´´

This PR does not break the old way. Both will work. (-:

2016-10-11 00:46 UTC, tizmagik commented
Thank you for this, this is great! I had no idea a decorator could also be a tagged template string, really neat!

With this, could you also update the README with this new interface? Especially to reflect your note from #6 : 

>About the peerDependency, i think since npm 3 they're not fetched automatically, but will return a warning if unresolved. Is this wanted? As long as the readme says
`npm install --save csjs react-csjs`
that would be fine. (Right now it just mentions react-csjs)

I'll try and spend some time later this week playing around with this PR to see how it affects the interface, if at all and get back to you. Thanks again!

2016-10-11 08:21 UTC, drcmda commented
Readme updated. Let me know if it needs changes.

2016-10-12 05:00 UTC, tizmagik commented
Hey @drcmda thanks again for this, I really want to merge this but I was hoping you can help me think through a few details first. I'm concerned that it could be somewhat confusing to users when to use

```js
import csjs from 'csjs';
```

vs

```js
import csjs from 'react-csjs';
```

- Why do I need `csjs` at all since It looks like `react-csjs` provides it?
- Or, maybe we should keep the decorator named as `withStyles` in the docs so that it can be used like this?

```jsx
import withStyles from 'react-csjs';

@withStyles`
  .foo {
    color: red;
  }
`
export default class Thing extends Component {
  render() {
    return <div className={this.props.classes.foo} />
  }
}
```

2016-10-12 05:02 UTC, tizmagik commented
Also, please be sure to add yourself as a contributor in package.json -- you'll be getting commit access once this PR is merged (my rule is 2 contributions grants commit privileges) 😄

2016-10-12 05:09 UTC, tizmagik requested changes
A few minor tweaks + some thoughts on how we can make the README a bit clearer about when to use `csjs` directly vs just `react-csjs`

2016-10-12 05:09 UTC, tizmagik commented on README.md
> +Or directly as a tagged decorator without the need of importing CSJS explicitly.
I think we should promote this style first, so the "Or" case is importing `csjs` explicitly

2016-10-12 05:09 UTC, tizmagik commented on README.md
>  ```
Add a note above this:

```
You'll need to install both `csjs` and `react-csjs` like so:
```

2016-10-12 05:09 UTC, tizmagik commented on README.md
> +`;
Does this actually require a semicolon here?

2016-10-12 05:09 UTC, tizmagik commented on src/index.js
> +    css = csjs(css, values);
Instead of modifying the `css` param, can we rename it in the signature and then use `css` locally here?

2016-10-12 05:11 UTC, tizmagik commented
Also, how were you testing this? I ask because #12 is landing soon and #14 might be useful to you.

2016-10-12 11:54 UTC, drcmda commented
@tizmagik 

> Why do I need csjs at all since It looks like react-csjs provides it?
You don't need to import csjs at all

>maybe we should keep the decorator named as withStyles in the docs so that it can be used like this?
The problem is that this will break postCSS and syntax highlighting. It needs the csjs`...` signature

The decorator (react-csjs) is a default export. By javascript concention they are nameless. You can use withStyles or anything really. And if you want to wrap stateless components you would. But since you can now pass stringn literals to the default export, you can export it as "csjs" and thereby profit from the babel passes.

2016-10-12 12:03 UTC, drcmda commented on src/index.js
> +    css = csjs(css, values);
css is later passed to csjs.getStyles(). Normally the function wants a csjs object, but with this it simply converts string literals to that csjs object which it later needs.

2016-10-12 12:25 UTC, drcmda commented on README.md
> +`;
I think it's safe to remove it 👍

2016-10-12 12:34 UTC, drcmda commented
I made the additions. I also opted for a little shorter CSS to keep examples tidy.

2016-10-12 13:53 UTC, tizmagik commented
> We don't need to import csjs at all, that's the cool thing about it :)

Right, I get that. What I'm saying is it wasn't completely clear to me as a user reading the README. But I think re-ordering the usage examples and some of the explanatory texts you added helped a lot. Thanks!

> The problem was that this will break postCSS and syntax highlighting. 3rd party plugs are hardcoded to the "csjs" signature and wouldn't work with "withStyles"

Ah, great point! 👍

2016-10-12 14:00 UTC, tizmagik commented on src/index.js
> +    css = csjs(css, values);
Right, but this breaks a lint rule `no-param-reassign`. If you lint this branch it should complain about this line (if it doesn't, something is wrong with the linter), so I suggest to do something like:

```js
export default function (userCss, values) {
  let css = userCss;
  
  if (Array.isArray(css)) {
  ...
```

2016-10-12 15:03 UTC, tizmagik commented
Labeling this as a `breaking change` since we'll no longer export a named `{withStyles}` function -- which I think is for the better.

2016-10-12 15:24 UTC, drcmda commented
@tizmagik the function name only plays a role internally, within the module. If you need to add prototypes to it etc. Since it is the default export outside it is always overridden by the import clause.

2016-10-12 15:29 UTC, drcmda commented
@tizmagik Looks good.

2016-10-12 15:31 UTC, drcmda commented on src/index.js
> +    css = csjs(css, values);
oh, wasn't aware of this ... will update asap

2016-10-12 15:57 UTC, tizmagik commented
One last thing then I think we can merge this. Can you add a test for using the tagged decorator syntax?

2016-10-12 16:01 UTC, drcmda commented
@tizmagik tbh, i wouldn't know where to start. I haven't done much testing. Could we merge and ask @wKovacs64 ?

2016-10-12 16:08 UTC, tizmagik commented
Sure, let's do that. I'll create an issue for a follow-on PR.

Thanks for this, great work!!

2016-10-12 16:08 UTC, tizmagik approved these changes

2016-10-12 16:08 UTC, merged